# Generated by Django 3.1.3 on 2025-10-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
