# Generated by Django 3.1.3 on 2025-10-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usersubscription_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='benefits',
            field=models.TextField(default=1, help_text='List of benefits, separated by commas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='screens',
            field=models.PositiveIntegerField(default=1, help_text='How many screens can watch at the same time'),
        ),
    ]
