# Generated by Django 3.1.3 on 2025-10-01 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0005_watchprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main title of the series', max_length=200)),
                ('description', models.TextField(help_text='A brief synopsis of the series')),
                ('release_year', models.IntegerField(help_text='The year the series was first released')),
                ('age_rating', models.CharField(help_text='e.g., 18+, PG-13', max_length=10)),
                ('ranking', models.CharField(blank=True, help_text='e.g., #5 in Series Today', max_length=100, null=True)),
                ('starring', models.TextField(help_text='List of main actors, separated by commas')),
                ('creators', models.CharField(help_text='The creator(s) of the series', max_length=255)),
                ('banner_image', models.ImageField(help_text='Wide banner image for the hero section', upload_to='series_banners/')),
                ('trailer_video', models.FileField(blank=True, help_text='Optional trailer video file', null=True, upload_to='trailers/')),
                ('genres', models.ManyToManyField(help_text='Select genres for this series', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(help_text='The number of the season (e.g., 1, 2, 3)')),
                ('release_date', models.DateField(blank=True, help_text='Release date of this season', null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='series.series')),
            ],
            options={
                'unique_together': {('series', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField(help_text='The number of the episode in the season')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_in_minutes', models.PositiveIntegerField(help_text='Duration of the episode in minutes')),
                ('thumbnail', models.ImageField(help_text='Thumbnail image for the episode', upload_to='episode_thumbnails/')),
                ('video_file', models.FileField(upload_to='episodes/')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='series.season')),
            ],
        ),
    ]
