# Generated by Django 3.1.3 on 2025-08-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('banner', models.ImageField(upload_to='banners/')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('age_limit', models.CharField(choices=[('7+', '7+'), ('13+', '13+'), ('16+', '16+'), ('18+', '18+')], max_length=10)),
                ('duration', models.CharField(max_length=20)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('starring', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('trailer', models.FileField(blank=True, null=True, upload_to='trailers/')),
                ('video', models.FileField(blank=True, null=True, upload_to='movies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
    ]
