# Generated by Django 3.1.3 on 2025-11-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20251102_1455'),
        ('movies', '0007_auto_20251102_1455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchprogress',
            unique_together={('user', 'profile', 'movie')},
        ),
    ]
