# Generated by Django 3.1.3 on 2025-11-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20251102_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actual_duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Actual length of the video file in minutes (e.g., 3)'),
        ),
    ]
